import type { DialectId, ModelEntity } from "./types";
import { DIALECTS } from "./dialects";
import { buildAllDdl, type TableNameOverrides } from "./ddl";
import { buildIndexes } from "./indexes";
import { buildInsertStatements } from "./inserts";

/**
 * One reviewable, re-runnable deployment script for a fresh database:
 * CREATE TABLE statements in foreign-key order, secondary indexes, then
 * deterministic sample rows. Powerduck only generates this text — it never
 * connects to a writable database or executes DDL/DML.
 */

export interface DeploymentResult {
  sql: string;
  tableCount: number;
  indexCount: number;
  insertRowCount: number;
  skippedForeignKeys: number;
}

export interface DeploymentOptions {
  ifNotExists?: boolean;
  overrides?: TableNameOverrides;
  /** Rows of deterministic sample data per table; 0 omits the data section. */
  sampleRows?: number;
}

function banner(title: string): string {
  return [
    "-- ---------------------------------------------------------------------------",
    `-- ${title}`,
    "-- Generated by Powerduck. Review before running. Powerduck never executes",
    "-- this script against a database; run it with an account you control.",
    "-- ---------------------------------------------------------------------------",
  ].join("\n");
}

export function buildDeploymentScript(
  dialectId: DialectId,
  entities: ModelEntity[],
  options: DeploymentOptions = {},
): DeploymentResult {
  const dialect = DIALECTS[dialectId];
  const overrides = options.overrides;
  const sections: string[] = [];

  const ddl = buildAllDdl(dialectId, entities, {
    ifNotExists: options.ifNotExists,
    overrides: options.overrides,
  });
  const indexes = buildIndexes(dialectId, entities, overrides);
  const sampleRows = options.sampleRows === undefined ? 5 : options.sampleRows;
  const inserts =
    sampleRows > 0 ? buildInsertStatements(dialectId, entities, sampleRows, overrides) : null;

  sections.push(banner(`Powerduck deployment script (${dialect.label})`));
  sections.push(`-- 1. Tables (${ddl.statements.length})\n\n${ddl.sql}`);

  if (indexes.statements.length) {
    sections.push(`-- 2. Secondary indexes (${indexes.statements.length})\n\n${indexes.sql}`);
  }

  if (inserts && inserts.rowCount > 0) {
    sections.push(`-- 3. Sample data (${inserts.rowCount} rows)\n\n${inserts.sql}`);
  }

  if (ddl.skippedForeignKeys.length) {
    const list = ddl.skippedForeignKeys.map((item) => `--   - ${item}`).join("\n");
    sections.push(
      `-- Note: ${ddl.skippedForeignKeys.length} foreign key constraint(s) were skipped because they would create a cycle:\n${list}`,
    );
  }

  return {
    sql: sections.join("\n\n"),
    tableCount: ddl.statements.length,
    indexCount: indexes.statements.length,
    insertRowCount: inserts?.rowCount ?? 0,
    skippedForeignKeys: ddl.skippedForeignKeys.length,
  };
}
