import type { DialectId, ModelColumn } from "./types";

/**
 * SQL dialect metadata: identifier quoting and JSON-Schema-to-SQL type
 * mapping for MySQL, SQL Server and Oracle. DDL structure lives in ddl.ts;
 * this module only answers per-column type questions.
 */

export interface Dialect {
  id: DialectId;
  label: string;
  quoteIdent: (name: string) => string;
  columnType: (column: ModelColumn) => string;
  /** Type used for unstructured JSON content. */
  jsonType: string;
  /** Integer primary key with auto-increment. */
  identityType: string;
  /** Statement terminator. */
  endStatement: string;
}

const DEFAULT_STRING = 255;

function enumLength(values: Array<string | number>): number {
  return Math.max(
    1,
    ...values.map((v) => String(v).length),
  );
}

const mysql: Dialect = {
  id: "mysql",
  label: "MySQL",
  quoteIdent: (name) => `\`${name.replace(/`/g, "``")}\``,
  jsonType: "JSON",
  identityType: "BIGINT AUTO_INCREMENT",
  endStatement: ";",
  columnType(column) {
    if (column.refEntityId) return "BIGINT";
    switch (column.jsonType) {
      case "integer":
        return column.format === "int64" ? "BIGINT" : "INT";
      case "number":
        if (column.format === "float") return "FLOAT";
        if (column.format === "double") return "DOUBLE";
        return "DECIMAL(18,4)";
      case "boolean":
        return "TINYINT(1)";
      case "object":
      case "array":
        return "JSON";
      case "string": {
        if (column.enumValues?.length) {
          return `ENUM(${column.enumValues
            .map((v) => `'${String(v).replace(/'/g, "''")}'`)
            .join(", ")})`;
        }
        switch (column.format) {
          case "date":
            return "DATE";
          case "time":
            return "TIME";
          case "date-time":
          case "timestamp":
            return "DATETIME(6)";
          case "binary":
          case "byte":
            return "BLOB";
          case "uuid":
            return "CHAR(36)";
          case "email":
          case "uri":
          case "url":
          case "hostname":
          case "password":
            return "VARCHAR(255)";
          default: {
            const length = column.maxLength ?? DEFAULT_STRING;
            return length > 16383 ? "TEXT" : `VARCHAR(${length})`;
          }
        }
      }
      default:
        return "TEXT";
    }
  },
};

const sqlserver: Dialect = {
  id: "sqlserver",
  label: "SQL Server",
  quoteIdent: (name) => `[${name.replace(/\]/g, "]]")}]`,
  jsonType: "NVARCHAR(MAX)",
  identityType: "BIGINT IDENTITY(1,1)",
  endStatement: ";",
  columnType(column) {
    if (column.refEntityId) return "BIGINT";
    switch (column.jsonType) {
      case "integer":
        return column.format === "int64" ? "BIGINT" : "INT";
      case "number":
        if (column.format === "float") return "REAL";
        if (column.format === "double") return "FLOAT";
        return "DECIMAL(18,4)";
      case "boolean":
        return "BIT";
      case "object":
      case "array":
        return "NVARCHAR(MAX)";
      case "string": {
        switch (column.format) {
          case "date":
            return "DATE";
          case "time":
            return "TIME";
          case "date-time":
          case "timestamp":
            return "DATETIME2";
          case "binary":
          case "byte":
            return "VARBINARY(MAX)";
          case "uuid":
            return "UNIQUEIDENTIFIER";
          default: {
            const length =
              column.maxLength ??
              (column.enumValues?.length ? enumLength(column.enumValues) : DEFAULT_STRING);
            return length > 4000 ? "NVARCHAR(MAX)" : `NVARCHAR(${length})`;
          }
        }
      }
      default:
        return "NVARCHAR(MAX)";
    }
  },
};

const oracle: Dialect = {
  id: "oracle",
  label: "Oracle",
  quoteIdent: (name) => `"${name.replace(/"/g, '""')}"`,
  jsonType: "CLOB",
  identityType: "NUMBER(19) GENERATED BY DEFAULT AS IDENTITY",
  endStatement: ";",
  columnType(column) {
    if (column.refEntityId) return "NUMBER(19)";
    switch (column.jsonType) {
      case "integer":
        return column.format === "int64" ? "NUMBER(19)" : "NUMBER(10)";
      case "number":
        if (column.format === "float") return "BINARY_FLOAT";
        if (column.format === "double") return "BINARY_DOUBLE";
        return "NUMBER(18,4)";
      case "boolean":
        return "NUMBER(1)";
      case "object":
      case "array":
        return "CLOB";
      case "string": {
        switch (column.format) {
          case "date":
            return "DATE";
          case "time":
            return "VARCHAR2(8 CHAR)";
          case "date-time":
          case "timestamp":
            return "TIMESTAMP(6)";
          case "binary":
          case "byte":
            return "BLOB";
          case "uuid":
            return "CHAR(36 CHAR)";
          default: {
            const length =
              column.maxLength ??
              (column.enumValues?.length ? enumLength(column.enumValues) : DEFAULT_STRING);
            return length > 4000 ? "CLOB" : `VARCHAR2(${length} CHAR)`;
          }
        }
      }
      default:
        return "CLOB";
    }
  },
};

export const DIALECTS: Record<DialectId, Dialect> = {
  mysql,
  sqlserver,
  oracle,
};

export const DIALECT_OPTIONS: Array<{ value: DialectId; label: string }> = [
  { value: "mysql", label: "MySQL" },
  { value: "sqlserver", label: "SQL Server" },
  { value: "oracle", label: "Oracle" },
];
